version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env.prod
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./static:/app/project/staticfiles
      - ./db_backups:/app/db_backups
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - ./media:/app/media
      - backup-volume:/backups
      - rclone-config:/root/.config/rclone
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
    name: django_postgres_data
  backup-volume:
  rclone-config: