version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env.prod
    volumes:
      - ./media:/app/media
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: