version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env.prod
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:14
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  celery-worker:
    build: .
    restart: always
    command: celery -A project worker --loglevel=info
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env.prod
    depends_on:
      - web
      - db
      - redis

  celery-beat:
    build: .
    restart: always
    command: celery -A project beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info
    volumes:
      - ./:/app
    env_file:
      - .env.prod
    depends_on:
      - web
      - db
      - redis

  nginx:
    image: nginx:1.21-alpine
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
    name: postgres_data
    external: true
  static_volume:
  media_volume:
  redis_data: