version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env.prod
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./static:/app/project/staticfiles   # Mount to the correct STATIC_ROOT path
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - ./media:/app/media
      - backup-volume:/backups
      - rclone-config:/root/.config/rclone  # Store rclone config in a volume
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

volumes:
  postgres-data:
  backup-volume:
  rclone-config:  # New volume for rclone configuration