name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy on VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
        cd /home/ubuntu/django-app/devops-oracle
        git reset --hard origin/main && git pull origin main
        
        # Check if containers are running for migration
        if docker-compose ps | grep -q "web.*Up"; then
          echo "Creating migrations inside running container..."
          docker-compose exec -T web python project/manage.py makemigrations
        else
          echo "Web container not running. Will create migrations during startup."
          # We'll handle this using an entry script
        fi
        
        # Rebuild and restart containers
        docker-compose down
        docker-compose up --build -d
        
        # Wait for web container to be ready
        echo "Waiting for web container to be fully up..."
        sleep 10
        
        # Verify migrations were applied
        docker-compose exec -T web python project/manage.py showmigrations | grep -q "\[X\]" && echo "✅ Migrations applied successfully"
        EOF