name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy on VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
        cd /home/ubuntu/django-app/devops-oracle
        git reset --hard origin/main && git pull origin main
        
        # Stop only the web container, leaving db untouched
        docker-compose stop web
        docker-compose rm -f web
        
        # Rebuild and start only the web container
        docker-compose build web
        docker-compose up -d
        
        # Verify containers are running
        docker-compose ps
        EOF