name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOSSH'
        # Navigate to your project directory
        cd /home/ubuntu/django-app/devops-oracle
        
        # Pull latest code
        git fetch origin main
        git reset --hard origin/main
        
        # Ensure environment files exist (first time only)
        mkdir -p .envs/.production
        
        # This would only run once to create initial env files if they don't exist
        if [ ! -f ".envs/.production/.django" ]; then
          echo "Creating Django environment file"
          # Create your .django file with appropriate settings
        fi
        
        if [ ! -f ".envs/.production/.postgres" ]; then
          echo "Creating Postgres environment file"
          # Create your .postgres file with appropriate settings
        fi
        
        # Start the services using production configuration
        docker-compose -f docker-compose.production.yml up -d --build
        
        echo "Deployment complete!"
        EOSSH